### ISSUE TITLE
Question about restarting the npm command

### ISSUE THREAD

**Issue by maggiechiuyeechan** [ericsoco/es7-sass-boilerplate#1]
Hi there! 

I'm a bit new at web development and was using your boilerplate for a project. But I seem to be failing to restart the project to be served to localhost:3000 once I quit it. I have just been running npm start again in the root directory - is there something I am doing wrong?

> es7-sass-boilerplate@0.0.1 start /Users/maggiechan/Documents/sites/yellowfever
> npm run sass && npm run watch & npm run serve

> es7-sass-boilerplate@0.0.1 serve /Users/maggiechan/Documents/sites/yellowfever
> serve dist

> es7-sass-boilerplate@0.0.1 sass /Users/maggiechan/Documents/sites/yellowfever
> node-sass --include-path scss scss/main.scss dist/main.css

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/maggiechan/Documents/sites/yellowfever/node_modules/.bin/node-sass:11:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sass"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! es7-sass-boilerplate@0.0.1 sass: `node-sass --include-path scss scss/main.scss dist/main.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the es7-sass-boilerplate@0.0.1 sass script 'node-sass --include-path scss scss/main.scss dist/main.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the es7-sass-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass --include-path scss scss/main.scss dist/main.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs es7-sass-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls es7-sass-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maggiechan/Documents/sites/yellowfever/npm-debug.log
module.js:471
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/maggiechan/Documents/sites/yellowfever/node_modules/.bin/serve:21:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! es7-sass-boilerplate@0.0.1 serve: `serve dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the es7-sass-boilerplate@0.0.1 serve script 'serve dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the es7-sass-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serve dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs es7-sass-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls es7-sass-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maggiechan/Documents/sites/yellowfever/npm-debug.log

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! es7-sass-boilerplate@0.0.1 start: `npm run sass && npm run watch & npm run serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the es7-sass-boilerplate@0.0.1 start script 'npm run sass && npm run watch & npm run serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the es7-sass-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run sass && npm run watch & npm run serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs es7-sass-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls es7-sass-boilerplate
npm ERR! There is likely additional logging output above.

**Comment by ericsoco** [comment]
Hm, not sure.

What version of node are you on? (`node --version`) Looks like this project wants 5+, and if you're "a bit new to web dev" you should be well above that.

You could also try `rm -rf node_modules` and `npm i` and `npm start` again.
